name: Fund Quant Analysis Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # 每天定时运行，UTC 时间 14:00 (北京时间 22:00)
    - cron: '0 14 * * *'

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
          
      - name: Install Python dependencies
        run: |
          pip install pandas numpy matplotlib
          
      - name: Run Quant Strategy Index Builder
        run: python simple_index.py
        
      - name: Commit and Push Results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated quant analysis pipeline update: NAV and Signal Count Plots'
          file_pattern: 'plots/*.png'
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          branch: main
