name: Test China C-Class Fund Screener

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run fund screener
      run: |
        python fund_screener_cn_cclass.py 2>&1 | tee output.log
        cat output.log

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: screener-output
        path: |
          recommended_cn_cclass_funds_2025.csv
          cn_fund_screener.log
          output.log
