name: Financial Data Analyzer

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 1 * * 1'  # 每周一上午 9 点 (UTC+8) 自动运行

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy beautifulsoup4 lxml selenium webdriver-manager yfinance akshare openpyxl

    - name: Run Python script
      run: python financial_data_analyzer.py
      
    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto update financial data" || echo "No changes to commit"
        git push
