name: Fund Analysis from CSV List

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install all dependencies
        run: |
          pip install --upgrade pip
          pip install pandas==1.5.3 numpy==1.24.4 matplotlib==3.7.5 seaborn==0.13.2 requests==2.31.0 akshare==1.16.72

      - name: Run fund analysis script
        run: python fund_analysis.py

      - name: Upload charts
        uses: actions/upload-artifact@v4
        with:
          name: fund-analysis-charts
          path: |
            net_value_chart.png
            drawdown_chart.png
