name: Financial Data Analyzer

on:
  workflow_dispatch:  # 允许手动触发
  # 如果需要定时运行，可以取消下面这行的注释
  # schedule:
  #   - cron: '0 1 * * 1'  # 每周一上午 9 点 (UTC+8) 自动运行

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy beautifulsoup4 lxml selenium webdriver-manager yfinance akshare openpyxl

    - name: Run Python script
      run: python financial_data_analyzer.py
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: financial-data-results
        path: |
          all_index_valuation.csv
          selected_low_valuation_indices.csv
          recommended_cn_funds.csv
          fund_analysis_*.json
          risk_metrics_*.json
