name: sub_checker_public_runner

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/sub_checker.yml'
      - 'sub_checker.py'

jobs:
  check_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Script
        uses: actions/checkout@v4 

      - name: Checkout Private Data Repo
        uses: actions/checkout@v4
        with:
          repository: qjlxg/362
          token: ${{ secrets.GH_TOKEN }}
          path: private_folder  

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install "httpx[http2]"

      - name: 执行检测脚本
        run: python sub_checker.py
        env:
          TZ: Asia/Shanghai
          DATA_PATH: private_folder/data

      - name: 提交并推送结果
        run: |
          cd private_folder
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/valid_subs.txt data/sub_links.txt
          if git diff --staged --quiet; then
            echo "没有检测到更新内容。"
          else
            git commit -m "Update subscriptions $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
        env:
          TZ: Asia/Shanghai
